### ISSUE TITLE
Stack overflow with pylyzer v0.0.60

### ISSUE THREAD

**Issue by TheSmilingTurtle** [mtshiba/pylyzer#101]
After running the following command
`pylyzer --verbose 2 -c "import numpy as np"`
I was presented with the following output:
```
Start checking: <string>

thread 'arrayterator' has overflowed its stack
fatal runtime error: stack overflow
[1]    729379 IOT instruction (core dumped)  pylyzer --verbose 2 -c "import numpy as np"
```
This happens repeatably.

**Comment by ibrokemypie** [comment]
Also able to repro this on v0.0.61

```
pylyzer --verbose 2 -c "import numpy as np"
Start checking: <string>

thread '_arrayterator_impl' has overflowed its stack
fatal runtime error: stack overflow
zsh: IOT instruction (core dumped)  pylyzer --verbose 2 -c "import numpy as np"
```

**Comment by mtshiba** [comment]
Maybe fixed in the latest version.

**Comment by Lexxxzy** [comment]
@mtshiba This also occures in 0.0.76 version. Reproduce with: 
```sh
pylyzer --verbose 2 -c "import pydantic"
```

Error:
thread 'pydantic' has overflowed its stack
fatal runtime error: stack overflow

**Comment by Rudo2204** [comment]
Still getting overflow error with `pydantic` on version 0.0.79
