### ISSUE TITLE
[BUG] Compilation error on `v0.0.11`

### ISSUE THREAD

**Issue by harshil21** [mtshiba/pylyzer#11]
Hi, I tried to run (`cargo install pylyzer`) but it failed :(

<details>

```
$ cargo install pylyzer
    Updating crates.io index
  Downloaded pylyzer v0.0.11
  Downloaded 1 crate (690.1 KB) in 3.41s
  Installing pylyzer v0.0.11
  Downloaded either v1.8.1
  Downloaded fake-simd v0.1.2
  Downloaded bitflags v1.3.2
  Downloaded rand_core v0.4.2
  Downloaded itoa v1.0.6
  Downloaded idna v0.3.0
  Downloaded rand_os v0.1.3
  Downloaded unicode-normalization v0.1.22
  Downloaded digest v0.8.1
  Downloaded diff v0.1.13
  Downloaded generic-array v0.12.4
  Downloaded rand_hc v0.1.0
  Downloaded rand_chacha v0.1.1
  Downloaded byte-tools v0.3.1
  Downloaded block-padding v0.1.5
  Downloaded lazy_static v1.4.0
  Downloaded aho-corasick v0.7.20
  Downloaded serde_repr v0.1.11
  Downloaded num-bigint v0.2.6
  Downloaded block-buffer v0.7.3
  Downloaded regex-syntax v0.6.28
  Downloaded ryu v1.0.13
  Downloaded form_urlencoded v1.1.0
  Downloaded unicode-xid v0.1.0
  Downloaded tinyvec v1.6.0
  Downloaded rand_core v0.3.1
  Downloaded unicode-xid v0.2.4
  Downloaded unicode-bidi v0.3.11
  Downloaded unicode-ident v1.0.8
  Downloaded num-traits v0.2.15
  Downloaded syn v1.0.109
  Downloaded strsim v0.10.0
  Downloaded rand_isaac v0.1.1
  Downloaded url v2.3.1
  Downloaded unic-ucd-ident v0.9.0
  Downloaded tinyvec_macros v0.1.1
  Downloaded num-integer v0.1.45
  Downloaded unic-char-property v0.9.0
  Downloaded rand_xorshift v0.1.1
  Downloaded quote v1.0.24
  Downloaded unic-char-range v0.9.0
  Downloaded sha2 v0.8.2
  Downloaded proc-macro2 v1.0.52
  Downloaded rand_pcg v0.1.2
  Downloaded unicode_names2 v0.4.0
  Downloaded libc v0.2.140
  Downloaded rand_jitter v0.1.4
  Downloaded itertools v0.8.2
  Downloaded siphasher v0.2.3
  Downloaded serde v1.0.155
  Downloaded new_debug_unreachable v1.0.4
  Downloaded rand v0.6.5
  Downloaded phf_generator v0.7.24
  Downloaded dirs v1.0.5
  Downloaded log v0.4.17
  Downloaded serde_derive v1.0.155
  Downloaded lsp-types v0.93.2
  Downloaded atty v0.2.14
  Downloaded serde_json v1.0.94
  Downloaded precomputed-hash v0.1.1
  Downloaded percent-encoding v2.2.0
  Downloaded typenum v1.16.0
  Downloaded regex v1.7.1
  Downloaded memchr v2.5.0
  Downloaded autocfg v1.1.0
  Downloaded docopt v1.1.1
  Downloaded opaque-debug v0.2.3
  Downloaded byteorder v1.4.3
  Downloaded bit-set v0.5.3
  Downloaded autocfg v0.1.8
  Downloaded bit-vec v0.6.3
  Downloaded ascii-canvas v2.0.0
  Downloaded fixedbitset v0.1.9
  Downloaded phf_shared v0.7.24
  Downloaded ordermap v0.3.5
  Downloaded ena v0.13.1
  Downloaded unic-emoji-char v0.9.0
  Downloaded unic-ucd-version v0.9.0
  Downloaded string_cache v0.7.5
  Downloaded py2erg v0.0.11
  Downloaded unic-common v0.9.0
  Downloaded petgraph v0.4.13
  Downloaded lalrpop-util v0.17.2
  Downloaded string_cache_codegen v0.4.4
  Downloaded string_cache_shared v0.3.0
  Downloaded rustpython-parser v0.1.2
  Downloaded els v0.1.20-nightly.0
  Downloaded erg_common v0.6.8-nightly.0
  Downloaded term v0.5.2
  Downloaded erg_parser v0.6.8-nightly.0
  Downloaded erg_compiler v0.6.8-nightly.0
  Downloaded lalrpop v0.17.2
  Downloaded 92 crates (5.1 MB) in 2.97s
   Compiling autocfg v1.1.0
   Compiling libc v0.2.140
   Compiling proc-macro2 v1.0.52
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.24
   Compiling rand_core v0.4.2
   Compiling syn v1.0.109
   Compiling serde v1.0.155
   Compiling serde_derive v1.0.155
   Compiling typenum v1.16.0
   Compiling siphasher v0.2.3
   Compiling memchr v2.5.0
   Compiling log v0.4.17
   Compiling autocfg v0.1.8
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_isaac v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling phf_shared v0.7.24
   Compiling erg_common v0.6.8-nightly.0
   Compiling byteorder v1.4.3
   Compiling string_cache_shared v0.3.0
   Compiling byte-tools v0.3.1
   Compiling block-padding v0.1.5
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.28
   Compiling cfg-if v1.0.0
   Compiling num-traits v0.2.15
   Compiling opaque-debug v0.2.3
   Compiling precomputed-hash v0.1.1
   Compiling strsim v0.10.0
   Compiling fake-simd v0.1.2
   Compiling aho-corasick v0.7.20
   Compiling new_debug_unreachable v1.0.4
   Compiling either v1.8.1
   Compiling fixedbitset v0.1.9
   Compiling tinyvec_macros v0.1.1
   Compiling rand_os v0.1.3
   Compiling dirs v1.0.5
   Compiling ordermap v0.3.5
   Compiling bit-vec v0.6.3
   Compiling itertools v0.8.2
   Compiling generic-array v0.12.4
   Compiling term v0.5.2
   Compiling tinyvec v1.6.0
   Compiling bit-set v0.5.3
   Compiling block-buffer v0.7.3
   Compiling digest v0.8.1
   Compiling petgraph v0.4.13
   Compiling ascii-canvas v2.0.0
   Compiling sha2 v0.8.2
   Compiling atty v0.2.14
   Compiling ena v0.13.1
   Compiling num-integer v0.1.45
   Compiling unic-common v0.9.0
   Compiling unic-char-range v0.9.0
   Compiling phf_generator v0.7.24
   Compiling unicode-xid v0.1.0
   Compiling diff v0.1.13
   Compiling lalrpop-util v0.17.2
   Compiling unic-char-property v0.9.0
   Compiling string_cache_codegen v0.4.4
   Compiling unicode-normalization v0.1.22
   Compiling unic-ucd-version v0.9.0
   Compiling num-bigint v0.2.6
   Compiling unicode-xid v0.2.4
   Compiling regex v1.7.1
   Compiling serde_json v1.0.94
   Compiling unicode-bidi v0.3.11
   Compiling percent-encoding v2.2.0
   Compiling string_cache v0.7.5
   Compiling idna v0.3.0
   Compiling form_urlencoded v1.1.0
   Compiling itoa v1.0.6
   Compiling ryu v1.0.13
   Compiling erg_compiler v0.6.8-nightly.0
   Compiling unic-emoji-char v0.9.0
   Compiling unic-ucd-ident v0.9.0
   Compiling erg_parser v0.6.8-nightly.0
   Compiling bitflags v1.3.2
   Compiling unicode_names2 v0.4.0
   Compiling serde_repr v0.1.11
   Compiling docopt v1.1.1
   Compiling url v2.3.1
   Compiling lalrpop v0.17.2
   Compiling lsp-types v0.93.2
   Compiling rustpython-parser v0.1.2
   Compiling els v0.1.20-nightly.0
error: `char::methods::<impl char>::from_u32` is not yet stable as a const fn
   --> /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/els-0.1.20-nightly.0/completion.rs:96:38
    |
96  |       pub const STD_ITEM: char = match char::from_u32(
    |  ______________________________________^
97  | |         CompletionOrder::Normal as u32
98  | |             + CompletionOrder::Builtin as u32
99  | |             + CompletionOrder::OtherNamespace as u32,
100 | |     ) {
    | |_____^

error: could not compile `els` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `pylyzer v0.0.11`, intermediate artifacts can be found at `/tmp/cargo-installo7hGOi`
```
</details>

Also, I tried installing the VSCode extension, but I don't see the pylyzer language server in my settings, am I doing something wrong? 
![image](https://user-images.githubusercontent.com/37377066/224748328-47c78c3e-398e-4ec7-b17c-8eae5e1406c1.png)

Edit: VSCode gave me this error:
```
[Error - 10:19:15 PM] pylyzer client: couldn't create connection to server.
Launching server using command pylyzer failed. Error: spawn pylyzer ENOENT
```

OS: Windows 11, but ran this on WSL2 (Ubuntu, kernel version: 5.15.90.1-microsoft-standard-WSL2)

**Comment by mtshiba** [comment]
This is not a bug. Please update to rust 1.67 or higher.

**Comment by mtshiba** [comment]
And the VSCode extension works just by installing it. There is no need to change its settings.

**Comment by harshil21** [comment]
> This is not a bug. Please update to rust 1.67 or higher.

Thanks! I updated to 1.68 (from 1.66) and it worked.

> And the VSCode extension works just by installing it. There is no need to change its settings.

I installed the latest version (0.1.3), and now it launches, but it fails shortly after:

<details>

```
[Info  - 5:14:33 PM] load_modules
[Info  - 5:14:33 PM] initializing ELS
[Info  - 5:14:36 PM] successfully bound
[Error - 5:14:36 PM] Request textDocument/codeAction failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 5:14:36 PM] Connection to server got closed. Server will restart.
true
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_parser-0.6.8-nightly.0/desugar.rs:830:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:14:36 PM] load_modules
[Info  - 5:14:36 PM] initializing ELS
[Info  - 5:14:36 PM] successfully bound
[Error - 5:14:36 PM] Request textDocument/codeAction failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 5:14:36 PM] Connection to server got closed. Server will restart.
true
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_parser-0.6.8-nightly.0/desugar.rs:830:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:14:37 PM] load_modules
[Info  - 5:14:37 PM] initializing ELS
[Info  - 5:14:37 PM] successfully bound
[Info  - 5:14:37 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 5:14:37 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_parser-0.6.8-nightly.0/desugar.rs:830:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:14:37 PM] Connection to server got closed. Server will restart.
true
[Info  - 5:14:37 PM] load_modules
[Info  - 5:14:37 PM] initializing ELS
[Info  - 5:14:37 PM] successfully bound
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_parser-0.6.8-nightly.0/desugar.rs:830:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:14:37 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 5:14:37 PM] Connection to server got closed. Server will restart.
true
[Info  - 5:14:38 PM] load_modules
[Info  - 5:14:38 PM] initializing ELS
[Info  - 5:14:38 PM] successfully bound
[Info  - 5:14:38 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 5:14:38 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_parser-0.6.8-nightly.0/desugar.rs:830:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 5:14:38 PM] The pylyzer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

</details>

**Comment by mtshiba** [comment]
> I installed the latest version (0.1.3) and didn't change any settings, and now it launches, but it fails shortly after:

This was a bug. It should be fixed in the latest version.

**Comment by harshil21** [comment]
> This was a bug. It should be fixed in the latest version.

Hmm, the extension still isn't working (v0.1.3). I updated pylyzer from cargo to v0.0.12.

<details>

```
[Info  - 12:05:30 PM] load_modules
[Info  - 12:05:31 PM] initializing ELS
[Info  - 12:05:31 PM] successfully bound
[Info  - 12:05:31 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 12:05:33 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 12:05:34 PM] Connection to server got closed. Server will restart.
true
thread 'main' panicked at 'internal error: entered unreachable code: {.default_backend = .default_backend}', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.8-nightly.1/context/register.rs:139:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 12:05:35 PM] initializing ELS
[Info  - 12:05:35 PM] successfully bound
[Info  - 12:05:35 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 12:05:35 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
thread 'main' panicked at 'internal error: entered unreachable code: {.default_backend = .default_backend}', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.8-nightly.1/context/register.rs:139:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 12:05:39 PM] Connection to server got closed. Server will restart.
true
[Info  - 12:05:39 PM] initializing ELS
[Info  - 12:05:39 PM] successfully bound
[Info  - 12:05:39 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 12:05:39 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
thread 'main' panicked at 'internal error: entered unreachable code: {.default_backend = .default_backend}', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.8-nightly.1/context/register.rs:139:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 12:05:42 PM] Connection to server got closed. Server will restart.
true
[Info  - 12:05:42 PM] load_modules
[Info  - 12:05:43 PM] initializing ELS
[Info  - 12:05:43 PM] successfully bound
[Info  - 12:05:43 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 12:05:43 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
thread 'main' panicked at 'internal error: entered unreachable code: {.default_backend = .default_backend}', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.8-nightly.1/context/register.rs:139:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 12:05:46 PM] Connection to server got closed. Server will restart.
true
[Info  - 12:05:46 PM] load_modules
[Info  - 12:05:46 PM] initializing ELS
[Info  - 12:05:46 PM] successfully bound
[Info  - 12:05:46 PM] textDocument/didOpen: file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
[Info  - 12:05:46 PM] checking file:///mnt/c/users/[omitted]/documents/pyprojects/python-telegram-bot/telegram/_bot.py
thread 'main' panicked at 'internal error: entered unreachable code: {.default_backend = .default_backend}', /home/hoppingturtles/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.8-nightly.1/context/register.rs:139:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 12:05:49 PM] The pylyzer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

</details>

I get the same error when trying from the command line: `pylyzer telegram/_bot.py`. The file I'm referencing is available [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/_bot.py), if that helps.

**Comment by mtshiba** [comment]
The relevant bugs have been fixed.

**Comment by huyhandes** [comment]
```
[Error - 6:15:41 PM] pylyzer client: couldn't create connection to server.
Launching server using command pylyzer failed. Error: spawn pylyzer ENOENT
```
Same on 0.1.7. I'm using rust and cargo 1.7.6. And vscode 1.86.2

**Comment by AugustDev** [comment]
Still a problem with latest release. Have rust installed.
